name: dotnet package

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
        - uses: actions/checkout@v4
        - name: Setup dotnet
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ matrix.dotnet-version }}
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: "20"
        - name: Install dependencies
          run: dotnet restore
        - name: Install testomat.io reporter
          run: npm install @testomatio/reporter
        - name: Test with dotnet
          run: dotnet test -l:nunit; $env:TESTOMATIO = "tstmt_ZkBAvUO-V5ze-kX5gWitypM0qVqEgrcfDA1733908621"; npx report-xml "./TestResults/**.xml" --lang="c#"
          # to set number of parallel subprocesses use flag  -- NUnit.NumberOfTestWorkers=4
          # to run tests by Category attribute, use flag -- NUnit.Where="cat=main" or --filter TestCategory="main"
          # make sure to pass all dotnet test properties like --filter and --environment before using -- NUnit properties